apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-monitor-bot
  namespace: default
  labels:
    k8s-app: endpoint-monitor-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: endpoint-monitor-bot
  template:
    metadata:
      labels:
        k8s-app: endpoint-monitor-bot
    spec:
      containers:
      - name: endpoint-monitor-bot
        imagePullPolicy: IfNotPresent
        image: madhukirans/endpoint-monitor-bot:0.1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/endpoints
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
      #  args:
      #    - --v=4
      #    - --namespace=default
      #serviceAccountName: sauron-operator
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-monitor-bot
  #annotations:
  #  external-dns.alpha.kubernetes.io/hostname: sauron-prod-ingress.sauron.us-ashburn-1.oracledx.com
  labels:
    k8s-app: endpoint-monitor-bot
spec:
  type: NodePort #LoadBalancer
  ports:
  - port: 8080
    nodePort: 30000
    name: http
  selector:
    k8s-app: endpoint-monitor-bot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    app: default-http-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-http-backend
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        # Any image is permissible as long as:
        # 1. It serves a 404 page at /
        # 2. It serves 200 on a /healthz endpoint
        image: gcr.io/google_containers/defaultbackend:1.4
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: default
  labels:
    app: default-http-backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: default-http-backend
---