---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: djmonitor
        image: madhukirans/monitor:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
